### PR TITLE
Inkycal v2.0.2: new feature-PR -> add image hashing

### PR DESCRIPTION
**Pull request by priv-kweihmann**
build md5 sum over the resulting assembled image(s) and
check against a stored hash file to determine if we really need
to update the screen.
Option can be controlled by new image_hash global option.

If info_section is enabled while image_hash is on,
the time of update will be stripped from the section,
as it is clearly not hashable.

In the end this enables us to update the information in the
background way more frequent without increasing the stress
caused to the display

Signed-off-by: Konrad Weihmann <kweihmann@outlook.com>

### CODE REVIEW

**Comment by priv-kweihmann** [comment]
@aceisace what's your take on this idea?

**Comment by aceisace** [comment]
@priv-kweihmann Apologies for the late reply and thanks for your pull request!
I like the idea of image hashing and I trust that you have done some sort of testing too, but I will test this myself and re-run all tests. 
One point though, could you please switch the target branch from main to `feature/venv` since main should is frozen except for hotfixes. This is also the branch for the next minor release scheduled for end of the next coming weeks, so feel free to create more PRs in that branch

**Comment by priv-kweihmann** [comment]
> @priv-kweihmann Apologies for the late reply and thanks for your pull request! I like the idea of image hashing and I trust that you have done some sort of testing too, but I will test this myself and re-run all tests. One point though, could you please switch the target branch from main to `feature/venv` since main should is frozen except for hotfixes. This is also the branch for the next minor release scheduled for end of the next coming weeks, so feel free to create more PRs in that branch

Done

**Comment by aceisace** [comment]
Awesome! Thank you very much for your PR, time and effort!
I'll merge this for now and will get back to the issue if need arises

**Pull request merged**
