### PR TITLE
hotfix for identifying all-day events

### PR DESCRIPTION
**Pull request by emilyboda**
warning: this code isn't nearly as pretty as the old code you had, but this is necessary for those of us in the western hemisphere for frequently have events starting at 0000 UTC. I really wanted to somehow use the iCalendar.all_day() function instead of all this mess I wrote, but I couldn't figure out how to make it work. Perhaps I will learn a little more and re-write it in the future. In the meantime, I highly recommend this fix, as it is very necessary.

the previous method of only checking if the beginning time was 0000 UTC wasn't sufficient. We have to add a check to see if the beginning and end time are 0000 UTC and also if the date it ends is more than the date it starts.

### CODE REVIEW

**Comment by aceisace** [comment]
@emilyboda Finally had the time to check this out in more detail. Indeed, addtional checks could be useful in a more accurate filter for all-day events, but it seems this code is causing an offset in the starting time.
For example, using the current code gives this image:


But when I use the code from this PR, the output looks like the following:


The time of all-day events changed from 00:00 to 1:00. I'd suggest reviewing the code to get the desired result.

**Comment by emilyboda** [comment]
Shoot, ok. Can you send me a link on discord to a calendar you're seeing this with? Also, what timezone are you in? I'm going to mess around with recreating your circumstances to see if I can get a fix for all timezones.

**Comment by aceisace** [comment]
Sure, I'll send you a link for testing purposes later on at Discord. Timezone is UTC+1, aka. CEST.

**Comment by emilyboda** [comment]
Hey @aceisace, I tried to do a little more troubleshooting, but I can't seem to replicate your issue. Are you sure that the events that are being time shifted are actually "all-day" events? On my calendar, anything that is an "all-day" event shows up with a blank space where the time would be, but your events show "00:00". I think if you sent me the calendar link that might help me troubleshoot.

**Comment by emilyboda** [comment]
@maweki are you interested in trying out this fix and seeing if you have the same problem that Ace did above? I think you and him are on the same timezone.

**Comment by maweki** [comment]
> @maweki are you interested in trying out this fix and seeing if you have the same problem that Ace did above? I think you and him are on the same timezone.

I believe this might be too involved and too much logic. Maybe you can explain what exactly is happening there.

Anyways:

https://github.com/aceisace/Inkycal/pull/161/files#diff-0a6d84d16400602054db1316b18e98ee7f29357f327fbd4e57b842af36d1b7bdR141

This doesn't do what you meant it to do. This probably needs to be

```python
if arrow.get(events.get('dtstart').dt).format('HH:mm') == arrow.get(events.get('dtend').dt).format('HH:mm') == '00:00':
```

instead of

```python
if arrow.get(events.get('dtstart').dt).format('HH:mm') and arrow.get(events.get('dtend').dt).format('HH:mm') == '00:00':
```

Currently this code only checks whether the start time is not `None` or empty.



https://github.com/aceisace/Inkycal/pull/161/files#diff-0a6d84d16400602054db1316b18e98ee7f29357f327fbd4e57b842af36d1b7bdR144-R147

This breaks on leap years


https://github.com/aceisace/Inkycal/pull/161/files#diff-0a6d84d16400602054db1316b18e98ee7f29357f327fbd4e57b842af36d1b7bdR150

This should probably be `if starts_and_ends_at_midnight and ends_on_a_later_day_than_it_started:`, no need to check for `True`.

https://github.com/aceisace/Inkycal/pull/161/files#diff-0a6d84d16400602054db1316b18e98ee7f29357f327fbd4e57b842af36d1b7bdR152-R153

Why is the timezone replaced in this case (this is surely the bug encountered by @aceisace )? This changes the point in time, while the point in time is kept in the other case.

https://github.com/aceisace/Inkycal/pull/161/files#diff-0a6d84d16400602054db1316b18e98ee7f29357f327fbd4e57b842af36d1b7bdR157-R158


Sorry, I didn't mean this to become a review, but I don't understand why this should be any more involved than checking whether it starts and ends at 0:00 (and the end be later than the start) in whatever the timezone(s) the user has chosen.

**Comment by emilyboda** [comment]
### First:
> This doesn't do what you meant it to do. This probably needs to be
> 
> `if arrow.get(events.get('dtstart').dt).format('HH:mm') == arrow.get(events.get('dtend').dt).format('HH:mm') == '00:00':`
>
> instead of
> 
> `if arrow.get(events.get('dtstart').dt).format('HH:mm') and arrow.get(events.get('dtend').dt).format('HH:mm') == '00:00':`

Can you explain a little more (maybe with an example) of why these two things don't do the same thing? I'm not opposed to using "==", but I just want to understand it a little more since it seems like it doesn't change anything on my calendar! Does using "and" not work with your calendar?

### Second
> This breaks on leap years

You're right, I need to fix it! Thankfully it only breaks on Dec 30th and 31st of leap years so I have a few more years before it will come into effect.

### Third
> This should probably be `if starts_and_ends_at_midnight and ends_on_a_later_day_than_it_started:`, no need to check for `True`.

Yes, I like this implementation a lot better. I'm going to change it!

### Fourth: the timezone thing
So, this is the hardest to explain.

The long story short, is that my usage of `.replace(tzinfo=timezone)` and `.to(timezone)` is the same as in ace's original ical_parser file. However, I changed the format of the code because we needed a more robust way to determine if something is an all-day event. That's the same problem you identified in the all_day method.

Here's the backstory:
I was going through the ics raw file to try to figure out what was happening with my events. I discovered that a normal event (say, at 3pm on a Saturday) has a timezone associated with it (in my case, EST). However, all-day events do not have any timezone associated with them and when they get imported they have UTC assigned as default. 

It's impossible for our program to know if a person intentionally created an event at 00:00 UTC or if the event was an all-day event that had no timezone associated with it and was assigned UTC when it got imported, so we needed a better way to determine if something is an all-day event.

The old ical_parser method is to go through all the events and
1) if the event does NOT start at 00:00, leave as is, with timezone intact (this is using `.to(timezone)` and is intending to catch regular, non-all-day events) 
or
2) else, strip out whatever timezone was associated and add the local timezone (this is using `.replace(tzinfo=timezone)` and is intending to handle all-day events)

There is no problem with using `.to(timezone)` and `.replace(tzinfo=timezone)` in this way. It is *correct* to use `.to(timezone)` on regular events and `.replace(tzinfo=timezone)` on all-day events.

However, because we are not determining all-day events properly, some events that start at 00:00 UTC are actually regular events. For example, 19:00 EST is equal to 00:00 UTC, so all of my events at 7pm EST were being converted to 00:00 EST.

I changed how we determine which events are all day. I decided that an all day event is:
1) it starts *and* ends at 00:00
2) it ends on a day later than when it starts

If both of those things are true, and it is indeed an all-day event, then we can use `.replace(tzinfo=timezone)` on it.

**Comment by maweki** [comment]
> Can you explain a little more (maybe with an example) of why these two things don't do the same thing?

`A and B == C` means `(bool(A) == True) and (B == C)`. I think you meant `A == C and B == C`. This can be shortened in python to `A == B == C` which gets expanded to `A == B and B == C` which is the same thing.

Now I understand the logic behind it. All-Day-Events are not associated a timezone. Makes sense.

But
https://github.com/aceisace/Inkycal/blob/1acdba6456c74fc9bc343ade00ca934c3cb07f63/inkycal/modules/ical_parser.py#L144-L147

I think it is enough to just check that start is before end. `arrow.get(events.get('dtstart').dt) < arrow.get(events.get('dtend').dt)` should suffice.

So if the event starts and ends at 0:00 UTC (maybe we should rather check for that - if TZ information is present, it should be honored) we would rather make it mean 0:00 Local time start and end.

Then identifying the all-day events (even those originally with TZ information) would still need #185 for events where start and end are in different timezones.


So the complete logic to identify an all-day-event I believe should be

```python
is_all_day_event = arrow.get(events.get('dtstart').dt).format('HH:mm') == arrow.get(events.get('dtend').dt).format('HH:mm') == '00:00' and arrow.get(events.get('dtstart').dt) < arrow.get(events.get('dtend').dt)
```

But if the event already is all-day with timezone information, we should not replace that timezone.

**Comment by emilyboda** [comment]
I concur with @maweki. I'm going to close this PR and create a new PR that includes the edited code they suggested above and also the code from their PR #185. I still am not sure what caused @aceisace's strange bug, but I would appreciate it if you both could test it and see if you find any bugs!

**Pull request closed without merging**
