### PR TITLE
fix loading from ics file

### PR DESCRIPTION
**Pull request by emilyboda**
I fixed the issue where you couldn't load from an ics file

### CODE REVIEW

**Comment by aceisace** [comment]
@emilyboda This code does work, just ran a few tests, but looks like some minor adjustments need to be made. When running the code from this PR, this is the output:
```python
Warning (from warnings module):
  File "/home/pi/Inkycal/inkycal/modules/ical_parser.py", line 98
    ical = [Calendar.from_ical(str(open(path).read())) for path in filepath]
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/pi/Desktop/mm2_ical.ics' mode='r' encoding='UTF-8'>
```

In short, the opened file is not closed, it remains open. With python, the following sytax is preferred when opening files:
```python
with open("somefile", mode="r") as file:    # open the file using a with...as statement using read mode
    file.do_something()                                 # do something with the contents of this file
```
After the file.do_something is executed, the file is automatically closed. An alternative approach is to use file.close(), like this:
```python
file = open("filepath", mode="r").read()
file.do_something()
file.close() # close the opened file
```

**Comment by aceisace** [comment]
@emilyboda So, I tested a few things and it looks like this is working as expected with the following change:
```python
    if isinstance(filepath, list):
      for path in filepath:
        with open(path, mode='r') as ical_file:
          ical = (Calendar.from_ical(ical_file.read()))
          self.icalendars.append(ical)  #<-- self.icalendars += ical

    elif isinstance(filepath, str):
      with open(filepath, mode='r') as ical_file:
        ical = (Calendar.from_ical(ical_file.read()))
        self.icalendars.append(ical) #<-- self.icalendars += ical
```

Could you let me know if it works for you as well? Thanks in advance.

**Comment by emilyboda** [comment]
Hey Ace-

Sorry for the delayed response! Yes, the changes you suggested work for me. I appreciate you taking the time to try to fix this edge case :)

**Comment by aceisace** [comment]
Thanks for your feedback, I'll implement this soon :)

**Pull request merged**
