### PR TITLE
updated inkycal_stocks

### PR DESCRIPTION
**Pull request by worstface**
updated inkycal_stocks to v0.5:
- Added improved precision by using yfinance priceHint info
- Added charts

changed yfinance requirement to >= 1.62 (fix for critical bug: https://github.com/ranaroussi/yfinance/issues/764)

added inkycal_xkcd module

### CODE REVIEW

**Comment by aceisace** [comment]
As per discussion on Discord, this can be merged in /development

**Comment by aceisace** [comment]
@worstface 
One of the simulation checks failed, below is the traceback with the following PR:
```python3
----------------------------------------------------------------------
Traceback (most recent call last):
  File "inkycal_stocks_test.py", line 79, in test_generate_image
    im_black, im_colour = module.generate_image()
  File "/home/runner/work/Inkycal/Inkycal/Inkycal/inkycal/modules/inkycal_stocks.py", line 108, in generate_image
    stockHistory = yfTicker.history("2d")
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/yfinance/base.py", line 156, in history
    data = data.json()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

May I ask you to kindly look into this? In the meanwhile, I've reverted the changes of this commit in /development

**Comment by worstface** [comment]
> @worstface
> One of the simulation checks failed, below is the traceback with the following PR:
> 
> ```python
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "inkycal_stocks_test.py", line 79, in test_generate_image
>     im_black, im_colour = module.generate_image()
>   File "/home/runner/work/Inkycal/Inkycal/Inkycal/inkycal/modules/inkycal_stocks.py", line 108, in generate_image
>     stockHistory = yfTicker.history("2d")
>   File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/yfinance/base.py", line 156, in history
>     data = data.json()
>   File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/requests/models.py", line 900, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/json/__init__.py", line 348, in loads
>     return _default_decoder.decode(s)
>   File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```
> 
> May I ask you to kindly look into this? In the meanwhile, I've reverted the changes of this commit in /development

that's exactly the mentioned critical bug in yfinance
it should work again after upgrading yfinance to 1.62

**Comment by aceisace** [comment]
@worstface Oh, that makes sense :)
I just check the workflow file, it was pointing at the main branch instead of the development branch. May I ask you to create the same PR pointed at the main branch? That way the tests will run correctly

**Comment by worstface** [comment]
@aceisace okay, created a fake PR for main: https://github.com/aceisace/Inkycal/pull/196

**Pull request merged**
