### PR TITLE
Quality of Life improvements

### PR DESCRIPTION
**Pull request by markusmo3**
I'm a software developer by day and most of the changes i did here are tailored to those who can code themselves, without compromising the normal users of Inkycal.
The individual changes are written in the git commit messages, the most important ones are:
* support hot-swapping of settings file
* updated info_section to use the tiny slkscr font by default
* yaml support and default values for some settings (better for human-writable settings files)
* ability to run inkycal only once and then exit (allows for complete customization of scheduling and module switching)
  * i also read up on battery powered pi zero. It seems that you could integrated a timer circuit that starts the pi zero every X minutes. The pi could then run inkycal once and shutdown completely, saving on battery power.

My `inky_run.py` looks like this now:
```python
from inkycal import Inkycal  # Import Inkycal
import time
import traceback

settingsFiles = [
#    'tweets.yml',
    'todoist.yml',
    'calendar.yml',
    'xkcd.yml',
]
i = 0
file_prefix = '/home/pi/inkycal_settings/'
while True:
    try:
        chosenFile = file_prefix + settingsFiles[i % len(settingsFiles)]
        print(f'### RUNNING INKYCAL WITH {chosenFile} for {i}th time')
        inky = Inkycal(settings_path=chosenFile, render=True)  # Initialise Inkycal
        # If your settings.json file is not in /boot, use the full path: inky = Inkycal('path/to/settings.json', render=True)
        inky.run_once()  # If there were no issues, you can run Inkycal nonstop
        print('sleeping 20 minutes...')
        time.sleep(60 * 20)
        i += 1
    except Exception as Error:
        traceback.print_exc()

```
which allows for the "switching" of modules i talked about on discord.
I know, its not an integrated, user accessible option, but for now it allows those that know python to get those features.

I also have a simplified runner for that inky script called `bginky.py`
```sh
PID=`ps -eaf | grep inky_run.py | grep -v grep | awk '{print $2}'`
if [[ "" !=  "$PID" ]]; then
  echo "killing $PID"
  kill -9 $PID
fi
nohup python3 -u inky_run.py >nohup.out 2>&1 &
```

Also, here is an example of a yaml settings file `xkcd.yml`
```yaml
---
model: epd_7_in_5_v3_colour
modules:
- position: 1
  name: Xkcd
  config:
    size:
    - 528
    - 860
    mode: random
    palette: bwr
    autoflip: true
    orientation: vertical
    padding_x: 0
    padding_y: 0
    fontsize: 24
    language: de
```

I'm open for any discussion or feedback that gets those changes integrated :D

### CODE REVIEW

**Comment by aceisace** [comment]
Phew, these are some large changes 😅 .

* support hot-swapping of settings file & yaml support and default values for some settings (better for human-writable settings files)

Inkycal used to have a simple .py settings file. As more users are not familiar with the syntax of python, e.g. String vs List, a web-ui was written, which simplified this part. As the software and the user community grew, there was a need for a more dynamic approach to the settings file.

Unfortunately, the web doesn't know python, but uses a more common format, .JSON. As a result, Inkycal eventually switched from the .py settings file to the .json settings file. I do not wish to change this behaviour as most users of Inkycal do not have much programming knowledge. Adding a YAML dependency is unfortunately not something that is on line with the future of  Inkycal, i.e. a system which can be managed fully over the web-ui. A good preview of this is InkycalOS, available from the release page.

Therefore I will have a hard time implementing YAML and even if, won't have much time to maintain it as good. The web-ui I'm working on is almost fully autonomous, it loads drivers, modules, settings etc. automatically and reflects changes on browser refresh and reboot.

* updated info_section to use the tiny slkscr font by default

This is on my to-do list, i.e. adding a bitmap font for e.g. the info section. The approach is a bit different though and does not rely on additional packages. Since there are separate images for black and coloured bands, there is also no need for explicit conversion to mode 1.

* ability to run inkycal only once and then exit 

This feature was planned for a later release, when some of the hurdles of a battery-powered Lipo could be resolved. I do have a prototype, but at the moment, I cannot test it for an extended time just yet. Once I have some progress, I'll post an update on Discord.
With regards to this function, I've added it the Projects's page so I can keep it as a to-do for the next release.


Unfortunately, this PR will therefore not be merged. But I am using this PR for reference purposes and adapting parts of the code for the next official release. Nonetheless, thank you very much for taking your time and effort for writing this PR! You do have much more programming expierence than me, and the code suggestions are professional too, but the cost of this PR is a bit too high to be worth, for more or less a single person, to fully maintain a repo this large.

**Comment by markusmo3** [comment]
As soon as is made my changes without proper git-etiquette i already kinda knew that this PR won't get through easily 😄
I won't go into a full discussion about what inkycal should have and should do, i just felt that inkycal is barely customizable and quite cumbersome without those changes (i.e. developer config files, default values, fontmode 1, runonce, logger-usage, dynamic module/settings loading, etc.)
Most of those issues are closely related to me being a programmer that really likes to customize his stuff and hates webuis though.
I love Inkycal and really honestly can't wait for more features 😆

Feel free to cherry pick the elements you like and adapt to your wishes.
If you want you can also call out some specific features you like and i'll try to create a new PR with just those integrated.

**Comment by worstface** [comment]
> As soon as is made my changes without proper git-etiquette i already kinda knew that this PR won't get through easily 😄
I think the biggest problem with this PR is that these changes break the Web UI. So your plan should have been to implement these changes without breaking the Web UI, which is an important part of the project. I think you could still do that. Maybe implement a few features or only one at a time. 😀

> Most of those issues are closely related to me being a programmer that really likes to customize his stuff and hates webuis though.
Fair enough, but not everyone using Inkycal is a programmer. There is also at least one programmer who likes to use the Web UI.😁

**Comment by aceisace** [comment]
Thank you for understanding, @markusmo3 . Thank you for the extra information, @worstface .
As Inkycal grew, the flexibility for developers has decreased too, but on the other hand, adapting to Gitflow, the web-ui and the additional limitations increased the user-friendliness of Inkycal (less issues related to settings file, no more sytax errors in settings file, clearer instructions about each parameter, also indiciating if it's required or optional).

Initially, I wasn't a big fan of the web-ui myself. But most users of Inkycal are non-developers, or at least have less knowledge with programming. Inkycal was also featured on the Raspberry Pi's official website for being one of the top-5 projects for beginners too. So I'd like to keep it a user-friendly. Of course there still is a long way until the web-ui regains nearly the same flexibility as without, but for this, you can look forward to the next release (or give InkycalOS a try).

Writing the new web-ui in python-flask, integrating it with apache2 and using a wsgi was worth it. While previously I had to adapt the web-ui on nearly every commit, the web-ui loads more or less everything dynamically. If you add a driver file in the drivers folder, it's shown on the web-ui as soon as this change is made. If you add a new module to Inkycal, it's reflected on the web-ui after simply refreshing the page, and it contains all the config too. 😄 

What's more is that although it's a web-ui, I've made the necessary changes to the web-ui to mimic the behaviour of an app (web-app). If you save the new web-ui on your homescreen, it has a nice icon, remembers login details and hides page navigation, making it look and feel like a real app. 😃 

So I'll pick up as much as I can from this PR while retaining the same core as the current release. If I run into an issue or something isn't clear in relation to this PR, I'll kindly ask for your help :)

**Comment by aceisace** [comment]
I'm closing this issue then. The bitmap font support can be tracked on #162 . As most of the web-ui now works in harmony with Inkycal, it won't be long until this feature can be implemented officially.

Once again, thank you for your pull request and for your time and effort!

**Pull request closed without merging**
