### PR TITLE
agendalist: add module

### PR DESCRIPTION
**Pull request by priv-kweihmann**
a slight modification of the agenda module.
Instead of printing each day and the attached events,
write just the events in chronological order.

Adds new parameters
- maxevents to control the number of events printed
- calname to print a custom name on top of each module entry
- timeindent/eventident to fine tune the indent of each item
- dt_format as a combination of date_format and time_format

Signed-off-by: Konrad Weihmann <kweihmann@outlook.com>

### CODE REVIEW

**Comment by aceisace** [comment]
Hi there @priv-kweihmann and thank you very much for your PR!
Could you please provide an image on how this is rendered on the display? Thanks in advance.

**Comment by priv-kweihmann** [comment]
agendalist
That is how it looks like

**Comment by priv-kweihmann** [comment]
@aceisace is there anything I can do to get this merged into the main tree?

**Comment by aceisace** [comment]
@priv-kweihmann 
Please fork the inkycal-modules-template repo ([see here](https://github.com/aceisace/inkycal-modules-template)) and add your module there instead . Just adding third-party modules to main is usually not a good idea due to maintainability and stability. Hence, add your changes there and then create a PR merging this into `feature/venv`.

**Comment by priv-kweihmann** [comment]
Will do

**Pull request closed without merging**
