### PR TITLE
Support for WaveShare V2 Colour Display 

### PR DESCRIPTION
**Pull request by ch3lmi**
This is to support the V2 version of the [WaveShare 12.48" colour display](https://www.waveshare.com/product/12.48inch-e-paper-module-b.htm#none;)

Successfully tested on such a display and running since a few months.

### CODE REVIEW

**Review by AndreasPuhl — APPROVED** [review]
Tested epd_12_in_48_colour.py on my hardware and it works perfectly.

**Comment by ch3lmi** [comment]
> Tested epd_12_in_48_colour.py on my hardware and it works perfectly. But should the weather module changes not be in their own pull request?

The weather module changes should definitely be in their different pull request, I have commented an existing PR with my suggestions as the[ originally requested PR ](https://github.com/aceisace/Inkycal/pull/194) creates an issue with some moonphases.
I somehow miserably failed to remove the weather changes from my display PR so reverted the weather module in my branch but apparently equally failed in doing so. So please only merge the inkycal/display/drivers/epd_12_in_48_colour_V2.py file if you can, otherwise happy to change my PR and exclude the weather file if someone tells me how.

**Review by achi87 — APPROVED** [review]
Improvement of red colour content (with Gooddisplay 12.48 colour V2)

**Comment by aceisace** [comment]
@ch3lmi @AndreasPuhl @achi87 
Thanks for the PR and testing! I've removed the weather module from this commit, so should be fine to merge 👍

**Pull request merged**
