### PR TITLE
Reworked Agenda to use less space

### PR DESCRIPTION
**Pull request by maweki**
This implementation collects all events starting on a date in a date item in order to use space more sparingly.

It creates a dictionary with all possible dates for the future and slots in the agenda items from the ical package. It allows for one additional entry per date and is a little less code. There is no longer a case distinction between an error in ical retrieval and success so fewer code paths. The drawing algorithm itself is the same and besides some variable renaming I kept it the same.

The issue that whole-day events spanning DST changes is shown with `00:00` is seperate (as you can see in both images)

Before:
IMG_20210326_225300_267

After:
IMG_20210326_222911_839

### CODE REVIEW

**Comment by aceisace** [comment]
Thanks for this PR @maweki . My exams will finish soon, then I'll test the suggested changes and give some additional feedback.

**Comment by maweki** [comment]
With this new data structure we can easily add multi-day events (spanning multiple days, like holidays) to all days in that timespan.

**Comment by aceisace** [comment]
Hi again, apologies for getting back late. Could you please have this merged in `feature/venv`? Then I can have it merged right away

**Comment by maweki** [comment]
Phew, all rebase, merge, and cherry-pick throw quite a few conflicts. It might take a bit. I possibly just do it by hand.

**Pull request closed without merging**
